github: [devinschumacher]
open_collective: devinschumacher
custom: [
"https://apps.serp.co/coursera-downloader",
"https://whop.com/serp-downloaders/coursera-downloader/",
"https://serp.co/products/coursera-downloader/reviews/"
]
